### ISSUE TITLE
RangeError: Array buffer allocation failed

### ISSUE THREAD

**Issue by vyrnix9582046173** [modulesio/node-native-browser-deps-linux#1]
Ubuntu 18.04
Node 11.10.1
Npm 6.7.0
```

> native-browser-deps@0.0.16 postinstall /home/chris/github/exokit/node_modules/native-browser-deps
> node postinstall.js


> native-browser-deps-linux@0.0.8 postinstall /home/chris/github/exokit/node_modules/native-browser-deps-linux
> node postinstall.js

/home/chris/github/exokit/node_modules/native-browser-deps-linux/postinstall.js:38
      throw err;
      ^

RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new Uint8Array (<anonymous>)
    at BrotliDecompress (/home/chris/github/exokit/node_modules/brotli/dec/decode.js:680:17)
    at unbr (/home/chris/github/exokit/node_modules/unbr/index.js:37:3)
    at Object.<anonymous> (/home/chris/github/exokit/node_modules/native-browser-deps-linux/postinstall.js:32:5)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! native-browser-deps-linux@0.0.8 postinstall: `node postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the native-browser-deps-linux@0.0.8 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/chris/.npm/_logs/2019-04-04T23_50_25_617Z-debug.log
```

**Comment by vyrnix9582046173** [comment]
This was due to not having enough memory free at the time.
